[workspace]
resolver = "2"
members = ["akrond", "akron-gui"]

[workspace.package]
version = "0.0.3"
edition = "2021"

[profile.release]
lto = true

[workspace.dependencies]
spaces_client = { path = "../spaced-spacesops/client" }
spaces_protocol = { path = "../spaced-spacesops/protocol" }
spaces_wallet = { path = "../spaced-spacesops/wallet" }
spaces_nums = { path = "../spaced-spacesops/nums" }
